# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create plugin ZIP
      run: |
        # Create a clean directory for the plugin
        mkdir spam-comment-cleaner
        
        # Copy plugin files (exclude development files)
        cp spam-comment-cleaner.php spam-comment-cleaner/
        cp README.md spam-comment-cleaner/
        
        # Create ZIP file
        zip -r spam-comment-cleaner.zip spam-comment-cleaner/
        
    - name: Get release info
      id: release_info
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Get latest commit message as release notes
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "notes=$COMMIT_MSG" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.release_info.outputs.version }}
        body: |
          ## Changes in version ${{ steps.release_info.outputs.version }}
          
          ${{ steps.release_info.outputs.notes }}
          
          ### Installation
          1. Download the `spam-comment-cleaner.zip` file below
          2. Go to WordPress Admin > Plugins > Add New > Upload Plugin
          3. Select the ZIP file and install
          4. Activate the plugin
        files: spam-comment-cleaner.zip
        draft: false
        prerelease: false
